### ISSUE TITLE
Firefox Beta support 

### ISSUE THREAD

**Issue by yellowsink** [iAlex11/PasteAndGo2#5]
**Is your feature request related to a problem? Please describe.**
I cannot use this with the Firefox Beta.

**Describe the solution you'd like**
I would like to be able to use TouchAndGo2 with the TestFlight beta for Firefox (bundle id `org.mozilla.ios.FirefoxBeta`)

**Describe alternatives you've considered**
Switching to standard Firefox.

**Additional context**
![1ADF955B-CA18-4105-A073-9C03909BA2CD](https://user-images.githubusercontent.com/19270622/99191112-764d7c80-2762-11eb-9643-6b3fc462c5d7.jpeg)

**Comment by alexmodrono** [comment]
Hey @cainy-a! I no longer maintain this project since I updated my device to iOS 14 and no longer have a jailbreak. Adding support for that browser is as simple as adding the bundleID to the browsers array and finding out what's the app's url scheme, I'm pretty sure someone else can do it. 

Sorry!

**Comment by yellowsink** [comment]
Ok thanks!
